use_frameworks!

platform :ios, '9.0'

target 'WDSelectAlertView_Example' do
  pod 'WDSelectAlertView', :path => '../'

  target 'WDSelectAlertView_Tests' do
    inherit! :search_paths

    
  end
end
